MvcStok/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;

namespace MvcStok.Controllers
{
    public class UrunController : Controller
    {
        // GET: Urun
        DbMvcStokEntities1 db = new DbMvcStokEntities1();
        public ActionResult Index(string p)
        {
            //var urunler = db.tblurunler.Where(x => x.durum == true).ToList();
            var urunler = db.tblurunler.Where(x => x.durum == true);
            if (!string.IsNullOrEmpty(p))
            {
                urunler = urunler.Where(x => x.ad.Contains(p) && x.durum == true);
            }
            return View(urunler.ToList());
        }
        [HttpGet]
        public ActionResult YeniUrun()
        {
            List<SelectListItem> ktg = (from x in db.tblkategori.ToList()
                                        select new SelectListItem
                                        {
                                            Text = x.ad,
                                            Value = x.id.ToString()
                                        }).ToList();
            ViewBag.drop = ktg;
            return View();
        }
        [HttpPost]
        public ActionResult YeniUrun(tblurunler t)
        {
            var ktgr = db.tblkategori.Where(x => x.id == t.tblkategori.id).FirstOrDefault();
            t.tblkategori = ktgr;
            db.tblurunler.Add(t);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult UrunGetir(int id)
        {
            List<SelectListItem> kat = (from x in db.tblkategori.ToList()
                                        select new SelectListItem
                                        {
                                            Text = x.ad,
                                            Value = x.id.ToString()
                                        }).ToList();
            var ktgr = db.tblurunler.Find(id);
            ViewBag.urunkategori = kat;
            return View("UrunGetir", ktgr);
        }
        public ActionResult UrunGuncelle(tblurunler p)
        {
            var urun = db.tblurunler.Find(p.id);
            urun.ad = p.ad;
            urun.marka = p.marka;
            urun.satisfiyat = p.satisfiyat;
            urun.alisfiyat = p.alisfiyat;
            urun.stok = p.stok;
            var ktg = db.tblkategori.Where(x => x.id == p.tblkategori.id).FirstOrDefault();
            urun.kategori = ktg.id;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult UrunSil(tblurunler p1)
        {
            var UrunBul = db.tblurunler.Find(p1.id);
            UrunBul.durum = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcStok/Views/Urun/Index.cshtml
@using MvcStok.Models.Entity;
@model List<tblurunler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("Index", "Urun", FormMethod.Get))
{
    <p>
        Ürün Adı : @Html.TextBox("p")
        <input type="submit" value="Ara" />
    </p>
}

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>ÜRÜN ADI</th>
        <th>MARKA</th>
        <th>STOK</th>
        <th>ALIŞ FİYAT</th>
        <th>SATIŞ FİYAT</th>
        <th>KATEGORİ</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.id</td>
            <td>@x.ad</td>
            <td>@x.marka</td>
            <td>@x.stok</td>
            <td>@x.alisfiyat</td>
            <td>@x.satisfiyat</td>
            <td>@x.tblkategori.ad</td>
            <td><a href="/Urun/UrunSil/@x.id" class="btn btn-danger">Sil</a></td>
            <td><a href="/Urun/UrunGetir/@x.id" class="btn btn-success">Güncelle</a></td>
        </tr>
    }
</table>
<a href="/Urun/YeniUrun/" class="btn btn-primary">Yeni Ürün Girişi</a>

MvcStok/Views/Urun/UrunGetir.cshtml
@model MvcStok.Models.Entity.tblurunler
@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("UrunGuncelle", "Urun", FormMethod.Post))
{
    <h2>Ürün Güncelleme</h2>
    @Html.HiddenFor(x => x.id, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.ad, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.marka, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.stok, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.alisfiyat, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.satisfiyat, new { @class = "form-control" })
    <br />
    @Html.DropDownListFor(x => x.tblkategori.id, (List<SelectListItem>)ViewBag.urunkategori, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Güncelle</button>
}

MvcStok/Views/Urun/YeniUrun.cshtml
@model MvcStok.Models.Entity.tblurunler
@{
    ViewBag.Title = "YeniUrun";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">
    <h2>Yeni Ürün Ekleme</h2>
    <br />
    <label>Ürün Adı</label>
    @Html.TextBoxFor(x => x.ad, new { @class = "form-control" })
    <br />

    <label>Marka</label>
    @Html.TextBoxFor(x => x.marka, new { @class = "form-control" })
    <br />

    <label>Stok</label>
    @Html.TextBoxFor(x => x.stok, new { @class = "form-control" })
    <br />

    <label>Alış Fiyatı</label>
    @Html.TextBoxFor(x => x.alisfiyat, new { @class = "form-control" })
    <br />

    <label>Satış Fiyatı</label>
    @Html.TextBoxFor(x => x.satisfiyat, new { @class = "form-control" })
    <br />

    <label>Kategori</label>
    @Html.TextBoxFor(x => x.kategori, new { @class = "form-control" })
    <br />


    <button class="btn btn-info">Kaydet</button>
</form>