MvcStok/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;
using PagedList;
using PagedList.Mvc;

namespace MvcStok.Controllers
{
    public class MusteriController : Controller
    {
        // GET: Musteri
        DbMvcStokEntities1 db = new DbMvcStokEntities1();
        [Authorize]
        public ActionResult Index(int sayfa = 1)
        {
            //var musterilistele = db.tblmusteri.ToList();
            var musterilistele = db.tblmusteri.Where(x => x.durum == true).ToList().ToPagedList(sayfa, 3);
            return View(musterilistele);
        }
        [HttpGet]
        public ActionResult YeniMusteri()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniMusteri(tblmusteri p)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniMusteri");
            }
            p.durum = true;
            db.tblmusteri.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult MusteriSil(tblmusteri p)
        {
            var MusteriBul = db.tblmusteri.Find(p.id);
            MusteriBul.durum = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult MusteriGetir(int id)
        {
            var mus = db.tblmusteri.Find(id);
            return View("MusteriGetir", mus);
        }
        public ActionResult MusteriGuncelle(tblmusteri t)
        {
            var mus = db.tblmusteri.Find(t.id);
            mus.ad = t.ad;
            mus.soyad = t.soyad;
            mus.sehir = t.sehir;
            mus.bakiye = t.bakiye;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcStok/Views/Musteri/Index.cshtml
@using MvcStok.Models.Entity;
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<tblmusteri>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>AD</th>
        <th>SOYADI</th>
        <th>ŞEHİR</th>
        <th>BAKİYE</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>

    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.id</td>
            <td>@x.ad</td>
            <td>@x.soyad</td>
            <td>@x.sehir</td>
            <td>@x.bakiye</td>
            <td><a href="/Musteri/MusteriSil/@x.id" class="btn btn-danger">Sil</a></td>
            <td><a href="/Musteri/MusteriGetir/@x.id" class="btn btn-success">Güncelle</a></td>
        </tr>
    }
</table>

@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new {sayfa}))

<a href="/Musteri/YeniMusteri/" class="btn btn-primary">Yeni Müşteri Ekle</a>

MvcStok/Views/Musteri/MusteriGetir.cshtml
@model MvcStok.Models.Entity.tblmusteri

@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("MusteriGuncelle", "Musteri", FormMethod.Post))
{
    <h2>Müşteri Güncelleme</h2>
    @Html.HiddenFor(x => x.id, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.ad, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.soyad, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.sehir, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.bakiye, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Güncelle</button>
}

MvcStok/Views/Musteri/YeniMusteri.cshtml
@model MvcStok.Models.Entity.tblmusteri

@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">
    <h2>Yeni Müşteri Ekleme</h2>
    <br />
    <label>Müşteri Adı</label>
    @Html.TextBoxFor(x => x.ad, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.ad, "", new { @style = "color:red" })
    <br />

    <label>Soyad</label>
    @Html.TextBoxFor(x => x.soyad, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.soyad, "", new { @style = "color:red" })

    <br />

    <label>Şehir</label>
    @Html.TextBoxFor(x => x.sehir, new { @class = "form-control" })
    <br />

    <label>Bakiye</label>
    @Html.TextBoxFor(x => x.bakiye, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>
</form>