MvcStok/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;

namespace MvcStok.Controllers
{
    public class KategoriController : Controller
    {
        // GET: Kategori
        DbMvcStokEntities1 db = new DbMvcStokEntities1();
        public ActionResult Index()
        {
            var kategoriler = db.tblkategori.ToList();
            return View(kategoriler);
        }
        [HttpGet]
        public ActionResult YeniKategori()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniKategori(tblkategori p)
        {
            db.tblkategori.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KategoriSil(int id)
        {
            var ktg = db.tblkategori.Find(id);
            db.tblkategori.Remove(ktg);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KategoriGetir(int id)
        {
            var ktg = db.tblkategori.Find(id);
            return View("KategoriGetir", ktg);
        }
        public ActionResult KategoriGuncelle(tblkategori k)
        {
            var ktg = db.tblkategori.Find(k.id);
            ktg.ad = k.ad;
            db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

MvcStok/Views/Kategori/Index.cshtml
@using MvcStok.Models.Entity;
@model List<tblkategori>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>KATEGORİ ADI</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
    </tr>
    @foreach(var x in Model)
            {
                <tr>
                    <td>@x.id</td>
                    <td>@x.ad</td>
                    <td><a href="/Kategori/KategoriSil/@x.id" class="btn btn-danger">Sil</a></td>
                    <td><a href="/Kategori/KategoriGetir/@x.id" class="btn btn-success">Güncelle</a></td>
                </tr>
            }
</table>
<a href="/Kategori/YeniKategori/" class="btn btn-primary">Yeni Kategori Ekle</a>

MvcStok/Views/Kategori/KategoriGetir.cshtml
@model MvcStok.Models.Entity.tblkategori
@{
    ViewBag.Title = "KategoriGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("KategoriGuncelle", "Kategori", FormMethod.Post))
{
    <h2>Yeni Kategori Güncelleme</h2>
    @Html.HiddenFor(x => x.id, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.ad, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Güncelle</button>
}

MvcStok/Views/Kategori/YeniKategori.cshtml
@model  MvcStok.Models.Entity.tblkategori
@{
    ViewBag.Title = "YeniKategori";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<form method="post">
    <h2>Yeni Kategori Ekleme</h2>
    <br />
    <label>Kategori Adını Giriniz...</label>
    <input type="text" class="form-control" name="ad" />
    <br />
    <button class="btn btn-info">Kaydet</button>
</form>