MvcStok/Controllers/GirisYapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;
using System.Web.Security;
namespace MvcStok.Controllers
{
    public class GirisYapController : Controller
    {
        // GET: GirisYap
        DbMvcStokEntities1 db = new DbMvcStokEntities1();
        public ActionResult Giris()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Giris(tbladmin t)
        {
            var bilgiler = db.tbladmin.FirstOrDefault(x => x.kullanici == t.kullanici && x.sifre == t.sifre);
            if(bilgiler != null)
            {
                FormsAuthentication.SetAuthCookie(bilgiler.kullanici,false);
                return RedirectToAction("Index", "Musteri");
            }
            else
            {
                return View();
            }
           
        }
    }
}

MvcStok/Views/GirisYap/Giris.cshtml
@{
    Layout = null;
}

<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Mvc5 Stok Projesi</title>
    <!-- meta tags -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="keywords" content="Art Sign Up Form Responsive Widget, Audio and Video players, Login Form Web Template, Flat Pricing Tables, Flat Drop-Downs, Sign-Up Web Templates,
		Flat Web Templates, Login Sign-up Responsive Web Template, Smartphone Compatible Web Template, Free Web Designs for Nokia, Samsung, LG, Sony Ericsson, Motorola Web Design" />
    <!-- /meta tags -->
    <!-- custom style sheet -->
    <link href="~/weblogin/css/style.css" rel="stylesheet" type="text/css" />
    <!-- /custom style sheet -->
    <!-- fontawesome css -->
    <link href="~/weblogin/css/fontawesome-all.css" rel="stylesheet" />
    <!-- /fontawesome css -->
    <!-- google fonts-->
    <link href="//fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <!-- /google fonts-->

</head>


<body>
    <h1>Giriş Form Paneli</h1>
    <div class=" w3l-login-form">
        <h2>Mvc5 Stok</h2>
        @using (Html.BeginForm("Giris", "GirisYap", FormMethod.Post))
        {

            <div class=" w3l-form-group">
                <label>Kullanıcı Adı:</label>
                <div class="group">
                    <i class="fas fa-user"></i>
                    <input type="text" class="form-control" placeholder="kullanıcı adı" required="required" name="kullanici" />
                </div>
            </div>
            <div class=" w3l-form-group">
                <label>Şifre:</label>
                <div class="group">
                    <i class="fas fa-unlock"></i>
                    <input type="password" class="form-control" placeholder="şifre" required="required" name="sifre" />
                </div>
            </div>
            <div class="forgot">
                <a href="#">Şifremi Unuttum?</a>
                <p><input type="checkbox">Beni Hatırla</p>
            </div>
            <button type="submit">Giriş Yap</button>
        }
        <p class=" w3l-register-p">Bir Hesabınız Yok mu?<a href="#" class="register"> Kayıt Ol</a></p>
    </div>
</body>

</html>